# Site settings
description: A blog from Damian Flynn, a Microsoft MVP and Cisco Champion
baseurl: "" # the subpath of your site, e.g. /blog/
url: http://blog.damianflynn.com
safe: false
title: Technical Blog
default_image: /images/default/surface.jpg
site_copyright: 2008-17 Damian Flynn.
site_url: http://blog.damianflynn.com
map_url: https://www.google.com/maps/place/Deer+Crest/@54.1205971,-9.240263,17z/data=!3m1!4b1!4m5!3m4!1s0x485938ff01b1f683:0xb699b4b3bca72fa0!8m2!3d54.1205971!4d-9.2380743

# Font Awesome version
fa_version: 4.6.0

# Build settings
timezone: Europe/Dublin
permalink: /:title/

kramdown:
  input: GFM
  syntax_highlighter: rouge

# Plugins
# sitemap: false in front matter of page to exclude
plugins:
  - jekyll-mentions
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed

# will convert @twitter-handle to the full twitter link in a post
jekyll-mentions: https://twitter.com

# User settings
username: DamianFlynn
user_description: Making Incrediable Technology, Increadibly Simple
user_title: Damian Flynn
user_logo: /assets/img/logos/damianflynn-logo-text-white.svg
user_icon: /assets/img/logos/damianflynn-icon-white.svg
email: info@damianflynn.com
twitter_username: damian_flynn
github_username:  damianflynn
disqus_username: damianflynn

# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']

# Url Shortener
shortener:
  basepath: /s/        # Path for stored redirects.
  preserve: false      # Keep previously generated files.
  salt:     "Damian"   # The optional salt, used when hasing the Unix time.

# Posting authors
Contributors:
  Damian Flynn:
    avatar: https://avatars2.githubusercontent.com/u/6288143?v=3
    title: Senior Principal Consultant, Cloud Architect
    desc: Focused on Making Incrediable Technology, Increadibly Simple.
    twitter: damian_flynn
    github: damianflynn
